import { SceneConfig } from "./types";

export const scenes: SceneConfig[] = [
  {
    id: "entry",
    interaction: "tap",
    texts: [],
    hint: "tap anywhere to begin",
    background: "ocean",
  },
  {
    id: "memory-1",
    interaction: "tap",
    texts: ["heyyy monisha", "it’s kinda crazy how everything led to this moment", "but there’s something I’ve been wanting to tell you"],
    hint: "tap to continue",
    background: "night",
  },
  {
    id: "hold-reveal",
    interaction: "hold",
    texts: ["Hold still.", "make sure you hold still ok "],
    hint: "press and hold",
    background: "deep",
    revealTexts: ["i don’t really know when it happened", "but talking to you just started feeling… easy"],
  },
  {
    id: "discovery",
    interaction: "discovery",
    texts: ["just a few things i like about you"],
    hint: "explore",
    background: "night",
    revealTexts: [
      "i like how genuine you are",
      "i like how you are very elegant with your way of words",
      "i like how you explain things when you’re excited",
      "i like how you carry yourself, it’s kinda cool",
    ],
  },
  {
    id: "drag-reveal",
    interaction: "drag",
    texts: ["slid to reveal"],
    hint: "drag to reveal",
    background: "deep",
    revealTexts: ["and what I want to say… has been there for a while now"],
    dragLabel: "slide",
  },
  {
    id: "build",
    interaction: "tap",
    texts: ["i’ve thought about this moment a lot", "More times than I can count", "and i don’t expect anything from you", "i just didn’t want to keep it to myself anymore"],
    hint: "tap",
    background: "glow",
  },
  {
    id: "pre-proposal",
    interaction: "hold",
    texts: ["i really enjoy talking to you… and somewhere along the way, it started becoming more than just friendship for me"],
    hint: "hold to continue",
    background: "deep",
    revealTexts: ["so yeah… this is the question i’ve been carrying"],
  },
  {
    id: "proposal",
    interaction: "proposal",
    texts: ["i don’t really know how to say this properly… would you like to be with me?"],
    background: "clear",
  },
  {
    id: "post-yes",
    interaction: "final",
    texts: ["letsssss gooooooo"],
    background: "glow",
  },
];
